nodeLinker: hoisted
shamefullyHoist: true

packages:
  - '.'

allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  better-sqlite3: false
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true

supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
