# pnpm-workspace.yaml
nodeLinker: hoisted
shamefullyHoist: true

packages:
  - '.'

publicHoistPattern:
  - '*unhead*'
  - '*@unhead*'
  - '*@tanstack/vue-table*'
  - 'types.*'
  - 'eslint.*'

allowBuilds:
  better-sqlite3: false
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true

supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64

overrides:
  # The precise lock that keeps your Vercel deployment stable and aligned with @nuxt/ui
  "@tanstack/vue-table": "^8.17.3"
