# pnpm-workspace.yaml
nodeLinker: hoisted
shamefullyHoist: true

packages:
  - '.'

# Move your custom hoist rules out of .npmrc and into camelCase format here:
publicHoistPattern:
  - '*unhead*'
  - '*@unhead*'
  - 'types.*'
  - 'eslint.*'

allowBuilds:
  better-sqlite3: false
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true

supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64

# The new canonical location for pnpm v12 overrides
overrides:
  "@tanstack/vue-table": "^8.11.2"