// English Index Page
export default defineEventHandler(() => {
  const enSermons = [
    { label: 'Advent Postil; Advent - Christmas', type: 'label' },

    { id: 1011, postil: 'Advent', tags: 'Epistle', label: '1.Sun. Advent', bible: 'Rom 13: 11-14' },
    { id: 1012, postil: 'Advent', tags: 'Gospel', label: '1.Sun. Advent', bible: 'Matt 21: 1-9' },
    { id: 1021, postil: 'Advent', tags: 'Epistle', label: '2.Sun. Advent', bible: 'Rom 15: 4-13' },
    { id: 1022, postil: 'Advent', tags: 'Gospel', label: '2.Sun. Advent', bible: 'Luk 21: 25-36' },
    { id: 1031, postil: 'Advent', tags: 'Epistle', label: '3.Sun. Advent', bible: '1 Cor 4: 1-5' },
    { id: 1032, postil: 'Advent', tags: 'Gospel', label: '3.Sun. Advent', bible: 'Matt 11: 2-10' },
    { id: 1041, postil: 'Advent', tags: 'Epistle', label: '4.Sun. Advent', bible: 'Phil 4: 4-7' },
    { id: 1042, postil: 'Advent', tags: 'Gospel', label: '4.Sun. Advent', bible: 'Joh 1: 19-28' },

    { type: 'separator' },
    { label: 'Christmas Postil; Christmas - Epiphany', type: 'label' },

    { id: 2001, postil: 'Christmas', tags: 'Epistle', label: 'Christmas D.', bible: 'Tit 2: 11-15' },
    { id: 2002, postil: 'Christmas', tags: 'Gospel', label: 'Christmas D.', bible: 'Luk 2: 1-14' },
    { id: 2011, postil: 'Christmas', tags: 'Epistle', label: 'Early Xmas', bible: 'Tit 3: 4-7' },
    { id: 2012, postil: 'Christmas', tags: 'Gospel', label: 'Early Xmas', bible: 'Luk 2: 15-20' },
    { id: 2013, postil: 'Christmas', tags: 'Epistle', label: 'Xmas Morn.', bible: 'Heb 1: 1-12' },
    { id: 2014, postil: 'Christmas', tags: 'Gospel', label: 'Main Xmas S.', bible: 'Joh 1: 1-14' },
    { id: 2021, postil: 'Christmas', tags: 'Epistle', label: 'St. Steph.\'s D.', bible: 'Acts 6: 8-14 & 7:54-60' },
    { id: 2022, postil: 'Christmas', tags: 'Gospel', label: 'St. Steph.\'s D.', bible: 'Matt 23: 34-39' },
    { id: 2031, postil: 'Christmas', tags: 'Epistle', label: 'St. John Day', bible: 'Ecclus 15: 1-8' },
    { id: 2032, postil: 'Christmas', tags: 'Gospel', label: 'St. John Day', bible: 'Joh 21: 19-23' },
    { id: 2041, postil: 'Christmas', tags: 'Epistle', label: 'Xmas Sunday', bible: 'Gal 4: 1-7' },
    { id: 2042, postil: 'Christmas', tags: 'Gospel', label: 'Xmas Sunday', bible: 'Luk 2: 33-40' },
    { id: 2051, postil: 'Christmas', tags: 'Epistle', label: 'New Year\'s D.', bible: 'Gal 3: 23-29' },
    { id: 2061, postil: 'Christmas', tags: 'Epistle', label: 'Epiphany', bible: 'Isaiah 60: 1-6' },
    { id: 2062, postil: 'Christmas', tags: 'Gospel', label: 'Epiphany', bible: 'Matt 2: 1-12' },

    { type: 'separator' },
    { label: 'Winter Postil; Epiphany - The Holy Week', type: 'label' },

    { id: 3111, postil: 'Winter', tags: 'Epistle', label: '1.Sun.af.Epi.', bible: 'Rom 12: 1-5' },
    { id: 3112, postil: 'Winter', tags: 'Gospel', label: '1.Sun.af.Epi.', bible: 'Luk 2: 42-52' },
    { id: 3113, postil: 'Winter', tags: 'Gospel', label: '1.Epi.2.ser.', bible: 'Luk 2: 42-52' },
    { id: 3121, postil: 'Winter', tags: 'Epistle', label: '2.Sun.af.Epi.', bible: 'Rom 12: 6-16' },
    { id: 3122, postil: 'Winter', tags: 'Gospel', label: '2.Sun.af.Epi.', bible: 'Joh 2: 1-11' },
    { id: 3131, postil: 'Winter', tags: 'Epistle', label: '3.Sun.af.Epi.', bible: 'Rom 12: 16-21' },
    { id: 3132, postil: 'Winter', tags: 'Gospel', label: '3.Sun.af.Epi.', bible: 'Matt 8: 1-13' },
    { id: 3141, postil: 'Winter', tags: 'Epistle', label: '4.Sun.af.Epi.', bible: 'Rom 13: 8-10' },
    { id: 3142, postil: 'Winter', tags: 'Gospel', label: '4.Sun.af.Epi.', bible: 'Matt 8: 23-27' },
    { id: 3151, postil: 'Winter', tags: 'Epistle', label: '5.Sun.af.Epi.', bible: 'Col 3: 12-17' },
    { id: 3152, postil: 'Winter', tags: 'Gospel', label: '5.Sun.af.Epi.', bible: 'Matt 13: 24-30' },

    { id: 3211, postil: 'Winter', tags: 'Epistle', label: '3.Sun.b.Lent', bible: '1 Cor 9: 24-10:5' },
    { id: 3212, postil: 'Winter', tags: 'Gospel', label: 'Septuagesima', bible: 'Matt 20: 1-16' },
    { id: 3221, postil: 'Winter', tags: 'Epistle', label: '2.Sun.b.Lent', bible: '2 Cor 11: 19-12:9' },
    { id: 3222, postil: 'Winter', tags: 'Gospel', label: 'Sexsagesima', bible: 'Luk 8: 5-15' },
    { id: 3231, postil: 'Winter', tags: 'Epistle', label: 'Sun.bef.Lent', bible: '1 Cor 13: 1-13' },
    { id: 3232, postil: 'Winter', tags: 'Gospel', label: 'Shrove Sun.', bible: 'Luk 18: 31-43' },

    { id: 3311, postil: 'Winter', tags: 'Epistle', label: '1.Sun. Lent', bible: '2 Cor 6: 1-10' },
    { id: 3312, postil: 'Winter', tags: 'Gospel', label: '1.Sun. Lent', bible: 'Matt 4: 1-11' },
    { id: 3321, postil: 'Winter', tags: 'Epistle', label: '2.Sun. Lent', bible: '1 Thess 4: 1-7' },
    { id: 3322, postil: 'Winter', tags: 'Gospel', label: '2.Sun. Lent', bible: 'Matt 15: 21-28' },
    { id: 3331, postil: 'Winter', tags: 'Epistle', label: '3.Sun. Lent', bible: 'Eph 5: 1-9' },
    { id: 3332, postil: 'Winter', tags: 'Gospel', label: '3.Sun. Lent', bible: 'Luk 11: 14-28' },
    { id: 3341, postil: 'Winter', tags: 'Epistle', label: '4.Sun. Lent', bible: 'Gal 4: 21-31' },
    { id: 3342, postil: 'Winter', tags: 'Gospel', label: '4.Sun. Lent', bible: 'Joh 6: 1-15' },

    /* id: 3344 Not translated to English "Marys Annunciation Day Luk 1: 26-38" */

    { id: 3351, postil: 'Winter', tags: 'Epistle', label: '5.Sun. Lent', bible: 'Heb 9: 11-15' },
    { id: 3352, postil: 'Winter', tags: 'Gospel', label: '5.Sun. Lent', bible: 'Joh 8: 46-59' },

    { id: 3401, postil: 'Winter', tags: 'Epistle', label: 'Palm Sunday', bible: 'Phil 2: 5-11' },
    { id: 3402, postil: 'Winter', tags: 'Gospel', label: 'The L.Supper', bible: '1 Cor 11: 23-26' },
    { id: 3403, postil: 'Winter', tags: 'Gospel', label: 'Good Friday', bible: 'Matt 27: 27-50' },

    { type: 'separator' },
    { label: 'Summer Postil; Easter - Pentecost', type: 'label' },

    { id: 4011, postil: 'Summer', tags: 'Epistle', label: 'Easter Sunday', bible: '1 Cor 5: 7-8' },
    { id: 4012, postil: 'Summer', tags: 'Gospel', label: 'Easter Sunday', bible: 'Mark 16: 1-8' },

    { id: 4021, postil: 'Summer', tags: 'Epistle', label: 'Easter Monday', bible: 'Acts 10: 34-43' },
    { id: 4022, postil: 'Summer', tags: 'Gospel', label: 'Easter Monday', bible: 'Luk 24: 13-35' },

    { id: 4031, postil: 'Summer', tags: 'Epistle', label: 'Easter Tuesday', bible: 'Acts 13: 26-39' },
    { id: 4032, postil: 'Summer', tags: 'Gospel', label: 'Easter Tuesday', bible: 'Luk 24: 36-47' },
    { id: 4033, postil: 'Summer', tags: 'Gospel', label: '2.Sermon', bible: 'Luk 24: 36-47' },

    { id: 4041, postil: 'Summer', tags: 'Epistle', label: '4.Easter day', bible: 'Col 3: 1-7' },

    { id: 4111, postil: 'Summer', tags: 'Epistle', label: '1.Sun.a.East.', bible: '1 Joh 5: 4-12' },
    { id: 4112, postil: 'Summer', tags: 'Gospel', label: '1.Sun.a.East.', bible: 'Joh 20: 19-31' },
    { id: 4113, postil: 'Summer', tags: 'Gospel', label: '2.sermon', bible: 'Joh 20: 19-31' },
    { id: 4121, postil: 'Summer', tags: 'Epistle', label: '2.Sun.a.East.', bible: '1 Pet 2: 20-25' },
    { id: 4122, postil: 'Summer', tags: 'Gospel', label: '2.Sun.a.East.', bible: 'Joh 10: 11-16' },
    { id: 4131, postil: 'Summer', tags: 'Epistle', label: '3.Sun.a.East.', bible: '1 Pet 2: 11-20' },
    { id: 4132, postil: 'Summer', tags: 'Gospel', label: '3.Sun.a.East.', bible: 'Joh 16: 16-23' },
    { id: 4141, postil: 'Summer', tags: 'Epistle', label: '4.Sun.a.East.', bible: 'James 1: 16-21' },
    { id: 4142, postil: 'Summer', tags: 'Gospel', label: '4.Sun.a.East.', bible: 'Joh 16: 5-15' },

    { id: 4152, postil: 'Summer', tags: 'Gospel', label: '5.Sun.a.East.', bible: 'Joh 16: 23-30' },

    { id: 4160, postil: 'Summer', tags: 'Epistle', label: 'Ascension Day', bible: 'Mark 16: 14-20' },

    { id: 4161, postil: 'Summer', tags: 'Epistle', label: '6.Sun.a.East.', bible: '1 Pet 4: 7-11' },
    { id: 4162, postil: 'Summer', tags: 'Gospel', label: '6.Sun.a.East.', bible: 'Joh 15: 26-16: 4' },

    { id: 4211, postil: 'Summer', tags: 'Epistle', label: 'Pentecost', bible: 'Acts 2: 1-13' },
    { id: 4212, postil: 'Summer', tags: 'Gospel', label: 'Pentecost', bible: 'Joh 14: 23-31' },
    { id: 4222, postil: 'Summer', tags: 'Epistle', label: '2.Pentecost.', bible: 'Joh 3: 16-21' },
    { id: 4232, postil: 'Summer', tags: 'Gospel', label: '3.Pentecost', bible: 'Joh 10: 1-10' },

    { type: 'separator' },
    { label: 'Trinity I Postil; Trinitatis - 12.Sun. after Trinitatis', type: 'label' },

    { id: 5001, postil: 'Trinity I', tags: 'Epistle', label: 'Trinitatis s.', bible: 'Rom 11: 33-36' },
    { id: 5002, postil: 'Trinity I', tags: 'Gospel', label: 'Trinitatis s.', bible: 'Joh 3: 1-15' },
    { id: 5003, postil: 'Trinity I', tags: 'Epistle', label: '2.sermon', bible: 'Rom 11: 33-36' },

    { id: 5011, postil: 'Trinity I', tags: 'Epistle', label: '1.Sun.a.Trin.', bible: '1 Joh 4: 16-21' },
    { id: 5012, postil: 'Trinity I', tags: 'Gospel', label: '1.Sun.a.Trin.', bible: 'Luk 16: 19-31' },
    { id: 5021, postil: 'Trinity I', tags: 'Epistle', label: '2.Sun.a.Trin.', bible: '1 Joh 3: 13-18' },
    { id: 5022, postil: 'Trinity I', tags: 'Gospel', label: '2.Sun.a.Trin.', bible: 'Luk 14: 16-24' },
    { id: 5031, postil: 'Trinity I', tags: 'Epistle', label: '3.Sun.a.Trin.', bible: '1 Pet 5: 5-11' },
    { id: 5032, postil: 'Trinity I', tags: 'Gospel', label: '3.Sun.a.Trin.', bible: 'Luk 15: 1-10' },
    { id: 5041, postil: 'Trinity I', tags: 'Epistle', label: '4.Sun.a.Trin.', bible: 'Rom 8: 18-22' },
    { id: 5042, postil: 'Trinity I', tags: 'Gospel', label: '4.Sun.a.Trin.', bible: 'Luk 6: 36-42' },
    { id: 5051, postil: 'Trinity I', tags: 'Epistle', label: '5.Sun.a.Trin.', bible: '1 Pet 3: 8-15' },
    { id: 5052, postil: 'Trinity I', tags: 'Gospel', label: '5.Sun.a.Trin.', bible: 'Luk 5: 1-11' },
    { id: 5061, postil: 'Trinity I', tags: 'Epistle', label: '6.Sun.a.Trin.', bible: 'Rom 6: 3-11' },
    { id: 5062, postil: 'Trinity I', tags: 'Gospel', label: '6.Sun.a.Trin.', bible: 'Matt 5: 20-26' },
    { id: 5071, postil: 'Trinity I', tags: 'Epistle', label: '7.Sun.a.Trin.', bible: 'Rom 6: 19-23' },
    { id: 5072, postil: 'Trinity I', tags: 'Gospel', label: '7.Sun.a.Trin.', bible: 'Mark 8: 1-9' },
    { id: 5081, postil: 'Trinity I', tags: 'Epistle', label: '8.Sun.a.Trin.', bible: 'Rom 8: 12-17' },
    { id: 5082, postil: 'Trinity I', tags: 'Gospel', label: '8.Sun.a.Trin.', bible: 'Matt 7: 15-23' },
    { id: 5091, postil: 'Trinity I', tags: 'Epistle', label: '9.Sun.a.Trin.', bible: '1 Cor 10: 6-13' },
    { id: 5092, postil: 'Trinity I', tags: 'Gospel', label: '9.Sun.a.Trin.', bible: 'Luk 16: 1-9' },
    { id: 5101, postil: 'Trinity I', tags: 'Epistle', label: '10.Sun.a.Trin.', bible: '1 Cor 12: 1-11' },
    { id: 5102, postil: 'Trinity I', tags: 'Gospel', label: '10.Sun.a.Trin.', bible: 'Luk 19: 41-48' },
    { id: 5111, postil: 'Trinity I', tags: 'Epistle', label: '11.Sun.a.Trin.', bible: '1 Cor 15: 1-10' },
    { id: 5112, postil: 'Trinity I', tags: 'Gospel', label: '11.Sun.a.Trin.', bible: 'Luk 18: 9-14' },
    { id: 5121, postil: 'Trinity I', tags: 'Epistle', label: '12.Sun.a.Trin.', bible: '2 Cor 3: 4-11' },
    { id: 5122, postil: 'Trinity I', tags: 'Gospel', label: '12.Sun.a.Trin.', bible: 'Mark 7: 31-37' },

    { type: 'separator' },
    { label: 'Trinity II Postil; 13.- 26.Sun. after Trinitatis', type: 'label' },

    { id: 6131, postil: 'Trinity II', tags: 'Epistle', label: '13.Sun.a.Trin.', bible: 'Gal 3: 15-22' },
    { id: 6132, postil: 'Trinity II', tags: 'Gospel', label: '13.Sun.a.Trin.', bible: 'Luk 10: 23-37' },
    { id: 6141, postil: 'Trinity II', tags: 'Epistle', label: '14.Sun.a.Trin.', bible: 'Gal 5: 16-24' },
    { id: 6142, postil: 'Trinity II', tags: 'Gospel', label: '14.Sun.a.Trin.', bible: 'Luk 17: 11-19' },
    { id: 6151, postil: 'Trinity II', tags: 'Epistle', label: '15.Sun.a.Trin.', bible: 'Gal 5: 25 - 6:10' },
    { id: 6152, postil: 'Trinity II', tags: 'Gospel', label: '15.Sun.a.Trin.', bible: 'Matt 6: 24-34' },
    { id: 6161, postil: 'Trinity II', tags: 'Epistle', label: '16.Sun.a.Trin.', bible: 'Eph 3: 13-21' },
    { id: 6162, postil: 'Trinity II', tags: 'Gospel', label: '16.Sun.a.Trin.', bible: 'Luk 7: 11-17' },
    { id: 6171, postil: 'Trinity II', tags: 'Epistle', label: '17.Sun.a.Trin.', bible: 'Eph 4: 1-6' },
    { id: 6172, postil: 'Trinity II', tags: 'Gospel', label: '17.Sun.a.Trin.', bible: 'Luk 14: 1-11' },
    { id: 6181, postil: 'Trinity II', tags: 'Epistle', label: '18.Sun.a.Trin.', bible: '1 Cor 1: 4-9' },
    { id: 6182, postil: 'Trinity II', tags: 'Gospel', label: '18.Sun.a.Trin.', bible: 'Matt 22: 34-46' },
    { id: 6191, postil: 'Trinity II', tags: 'Epistle', label: '19.Sun.a.Trin.', bible: 'Eph 4: 22-28' },
    { id: 6192, postil: 'Trinity II', tags: 'Gospel', label: '19.Sun.a.Trin.', bible: 'Matt 9: 1-8' },
    { id: 6201, postil: 'Trinity II', tags: 'Epistle', label: '20.Sun.a.Trin.', bible: 'Eph 5: 15-21' },
    { id: 6202, postil: 'Trinity II', tags: 'Gospel', label: '29.Sun.a.Trin.', bible: 'Matt 22: 1-14' },
    { id: 6211, postil: 'Trinity II', tags: 'Epistle', label: '21.Sun.a.Trin.', bible: 'Eph 6: 10-17' },
    { id: 6212, postil: 'Trinity II', tags: 'Gospel', label: '21.Sun.a.Trin.', bible: 'Joh 4: 46-54' },
    { id: 6215, postil: 'Trinity II', tags: 'Gospel', label: 'All Saint\'s Day', bible: 'Matt 5: 1-12' },
    { id: 6221, postil: 'Trinity II', tags: 'Epistle', label: '22.Sun.a.Trin.', bible: 'Phil 1: 3-11' },
    { id: 6222, postil: 'Trinity II', tags: 'Gospel', label: '22.Sun.a.Trin.', bible: 'Matt 18: 23-35' },
    { id: 6231, postil: 'Trinity II', tags: 'Epistle', label: '23.Sun.a.Trin.', bible: 'Phil 3: 17-21' },
    { id: 6232, postil: 'Trinity II', tags: 'Gospel', label: '23.Sun.a.Trin.', bible: 'Matt 22: 15-22' },
    { id: 6241, postil: 'Trinity II', tags: 'Epistle', label: '24.Sun.a.Trin.', bible: 'Col 1: 3-14' },
    { id: 6242, postil: 'Trinity II', tags: 'Gospel', label: '24.Sun.a.Trin.', bible: 'Matt 9: 18-26' },
    { id: 6251, postil: 'Trinity II', tags: 'Epistle', label: '25.Sun.a.Trin.', bible: '1 Thess 4: 13-18' },
    { id: 6252, postil: 'Trinity II', tags: 'Gospel', label: '25.Sun.a.Trin.', bible: 'Matt 24: 15-28' },
    { id: 6261, postil: 'Trinity II', tags: 'Epistle', label: '26.Sun.a.Trin.', bible: '2 Thess 1: 3-10' },
    { id: 6262, postil: 'Trinity II', tags: 'Gospel', label: '26.Sun.a.Trin.', bible: 'Matt 25: 31-42' },

    { type: 'separator' }
  ]

  return enSermons
})
